#!/bin/bash
export SHARELATEX_CONFIG=/etc/sharelatex/settings.js
export SESSION_SECRET="${SESSION_SECRET:-change-this-session-secret-in-production}"
exec /sbin/setuser www-data /usr/bin/yarn --cwd /var/www/sharelatex workspace @overleaf/filestore start >> /var/log/sharelatex/filestore.log 2>&1
