#!/bin/bash
export SHARELATEX_CONFIG=/etc/sharelatex/settings.js
export MONGO_CONNECTION_STRING="${MONGO_CONNECTION_STRING:-${SHARELATEX_MONGO_URL:-${MONGO_URL:-mongodb://mongo/sharelatex}}}"
export AUTO_CONFIRM_EMAIL_INTERVAL_MS="${AUTO_CONFIRM_EMAIL_INTERVAL_MS:-5000}"

exec /sbin/setuser www-data /usr/bin/yarn --cwd /var/www/sharelatex node /opt/sharelatex/auto_confirm_emails.mjs >> /var/log/sharelatex/email-autoconfirm.log 2>&1
