#!/bin/bash
export SHARELATEX_CONFIG=/etc/sharelatex/settings.js
export SESSION_SECRET="${SESSION_SECRET:-change-this-session-secret-in-production}"

NODE_PARAMS=""
if [ "$DEBUG_NODE" == "true" ]; then
    echo "running debug - clsi"
    NODE_PARAMS="--inspect=0.0.0.0:30130"
fi

# Set permissions on docker.sock if present,
# To enable sibling-containers (see entrypoint.sh in clsi project)
if [ -e '/var/run/docker.sock' ]; then
  echo ">> Setting permissions on docker socket"
  DOCKER_GROUP=$(stat -c '%g' /var/run/docker.sock)
  groupadd --non-unique --gid ${DOCKER_GROUP} dockeronhost
  usermod -aG dockeronhost www-data
fi

# Copies over CSLI synctex to the host mounted volume, so it
# can be subsequently mounted in TexLive containers on Sandbox Compilation
SYNCTEX=/var/lib/sharelatex/bin/synctex
if [ ! -f "$SYNCTEX" ]; then
    if [ "$DISABLE_SYNCTEX_BINARY_COPY" == "true" ]; then
        echo ">> Copy of synctex executable disabled by DISABLE_SYNCTEX_BINARY_COPY flag, feature may not work"
    elif [ -f /var/www/sharelatex/clsi/bin/synctex ]; then
        echo ">> Copying synctex executable to the host"
        mkdir -p $(dirname $SYNCTEX )
        cp /var/www/sharelatex/clsi/bin/synctex $SYNCTEX
    else
        echo ">> synctex executable not found, skipping copy"
    fi
fi

exec /sbin/setuser www-data env NODE_OPTIONS="$NODE_PARAMS" /usr/bin/yarn --cwd /var/www/sharelatex workspace @overleaf/clsi start >> /var/log/sharelatex/clsi.log 2>&1
