#!/bin/bash
export SHARELATEX_CONFIG=/etc/sharelatex/settings.js
export SESSION_SECRET="${SESSION_SECRET:-change-this-session-secret-in-production}"

NODE_PARAMS=""
if [ "$DEBUG_NODE" == "true" ]; then
    echo "running debug - chat"
    NODE_PARAMS="--inspect=0.0.0.0:30100"
fi

exec /sbin/setuser www-data env NODE_OPTIONS="$NODE_PARAMS" /usr/bin/yarn --cwd /var/www/sharelatex workspace @overleaf/chat start >> /var/log/sharelatex/chat.log 2>&1
